-- Migração inicial Supabase/PostgreSQL. Execute em projeto novo pelo SQL Editor.
-- Não contém senhas ou chaves. Não substitui o banco local automaticamente.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE public.profiles(id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,name text NOT NULL,email text NOT NULL,role text NOT NULL DEFAULT 'VENDEDOR' CHECK(role IN ('ADMIN','VENDEDOR','PRODUCAO','FINANCEIRO')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.salespeople(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),profile_id uuid UNIQUE REFERENCES public.profiles(id),name text NOT NULL,phone text,email text,city text,region text,active boolean NOT NULL DEFAULT true,commission_type text NOT NULL DEFAULT 'percent' CHECK(commission_type IN ('percent','item','plate','margin','custom')),commission_value numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE public.territories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),salesperson_id uuid REFERENCES public.salespeople(id),state text,city text,region text,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(state,city,region));
CREATE TABLE public.companies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,legal_name text,document text,contact text,phone text,whatsapp text,email text,address text,city text NOT NULL,neighborhood text,state text,postal_code text,segment text,origin text,instagram text,facebook text,website text,notes text,status text NOT NULL DEFAULT 'Novo lead',salesperson_id uuid REFERENCES public.salespeople(id),is_customer boolean NOT NULL DEFAULT false,place_id text UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE public.leads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),stage text NOT NULL DEFAULT 'Novo lead',loss_reason text,last_contact_at timestamptz,next_contact_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),status text NOT NULL DEFAULT 'Ativo',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),name text NOT NULL,phone text,email text,position text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.activities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),user_id uuid REFERENCES public.profiles(id),type text NOT NULL,description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.followups(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),responsible_id uuid REFERENCES public.profiles(id),scheduled_at timestamptz NOT NULL,reason text NOT NULL,notes text,done boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.vendors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,document text,phone text,email text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inventory_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,unit text NOT NULL DEFAULT 'un',quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK(quantity>=0),minimum numeric(14,3) NOT NULL DEFAULT 0,cost integer NOT NULL DEFAULT 0 CHECK(cost>=0),vendor_id uuid REFERENCES public.vendors(id),last_purchase_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,sku text UNIQUE NOT NULL,category text NOT NULL,description text,cost integer NOT NULL CHECK(cost>=0),price integer NOT NULL CHECK(price>=0),active boolean NOT NULL DEFAULT true,is_plate boolean NOT NULL DEFAULT true,uses_nfc boolean NOT NULL DEFAULT false,uses_acrylic boolean NOT NULL DEFAULT false,controls_stock boolean NOT NULL DEFAULT false,unit text NOT NULL DEFAULT 'un',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE public.product_components(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES public.products(id),inventory_id uuid NOT NULL REFERENCES public.inventory_items(id),quantity numeric(14,3) NOT NULL CHECK(quantity>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(product_id,inventory_id));
CREATE TABLE public.sales(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),number bigint GENERATED ALWAYS AS IDENTITY UNIQUE,company_id uuid NOT NULL REFERENCES public.companies(id),salesperson_id uuid REFERENCES public.salespeople(id),date date NOT NULL,total integer NOT NULL CHECK(total>=0),cost integer NOT NULL CHECK(cost>=0),profit integer NOT NULL,plates integer NOT NULL DEFAULT 0,commission integer NOT NULL DEFAULT 0,commission_rule jsonb NOT NULL,method text NOT NULL,due_date date NOT NULL,notes text,cancelled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.sale_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sale_id uuid NOT NULL REFERENCES public.sales(id),product_id uuid NOT NULL REFERENCES public.products(id),product_name text NOT NULL,quantity integer NOT NULL CHECK(quantity>0),price integer NOT NULL CHECK(price>=0),cost integer NOT NULL CHECK(cost>=0),is_plate boolean NOT NULL DEFAULT false,margin numeric NOT NULL,components_snapshot jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sale_id uuid NOT NULL REFERENCES public.sales(id),amount integer NOT NULL CHECK(amount>0),method text NOT NULL,date date NOT NULL,installment integer,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sale_id uuid NOT NULL UNIQUE REFERENCES public.sales(id),status text NOT NULL DEFAULT 'Pedido recebido',promised_date date,notes text,produced_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES public.orders(id),sale_item_id uuid NOT NULL REFERENCES public.sale_items(id),quantity integer NOT NULL CHECK(quantity>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.production_tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES public.orders(id),assigned_to uuid REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'Pendente',notes text,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inventory_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),inventory_id uuid NOT NULL REFERENCES public.inventory_items(id),user_id uuid REFERENCES public.profiles(id),order_id uuid REFERENCES public.orders(id),quantity numeric(14,3) NOT NULL,type text NOT NULL,description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.purchases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),vendor_id uuid REFERENCES public.vendors(id),date date NOT NULL,total integer NOT NULL CHECK(total>=0),method text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.purchase_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),purchase_id uuid NOT NULL REFERENCES public.purchases(id),inventory_id uuid NOT NULL REFERENCES public.inventory_items(id),quantity numeric(14,3) NOT NULL CHECK(quantity>0),total integer NOT NULL CHECK(total>=0),unit_cost integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.expenses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),description text NOT NULL,category text NOT NULL,amount integer NOT NULL CHECK(amount>0),date date NOT NULL,due_date date,paid_at timestamptz,salesperson_id uuid REFERENCES public.salespeople(id),city text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.commissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sale_id uuid NOT NULL REFERENCES public.sales(id),salesperson_id uuid NOT NULL REFERENCES public.salespeople(id),rule_snapshot jsonb NOT NULL,amount integer NOT NULL,status text NOT NULL DEFAULT 'Pendente',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.goals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),salesperson_id uuid REFERENCES public.salespeople(id),period text NOT NULL,start_date date,end_date date,amount integer NOT NULL CHECK(amount>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
-- Cache Google não deve persistir respostas de Places. Apenas identificador e horário.
CREATE TABLE public.google_places(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),place_id text UNIQUE NOT NULL,google_last_synced_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ranking_checks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),term text NOT NULL,location text NOT NULL,position integer CHECK(position>0),checked_at timestamptz NOT NULL,source text NOT NULL,notes text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.routes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,date date NOT NULL,salesperson_id uuid REFERENCES public.salespeople(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.route_stops(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),route_id uuid NOT NULL REFERENCES public.routes(id),company_id uuid NOT NULL REFERENCES public.companies(id),position integer NOT NULL,status text NOT NULL DEFAULT 'Pendente',visited_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(route_id,company_id));
CREATE TABLE public.attachments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid REFERENCES public.companies(id),sale_id uuid REFERENCES public.sales(id),order_id uuid REFERENCES public.orders(id),storage_path text NOT NULL,name text NOT NULL,type text NOT NULL,size_bytes bigint,uploaded_by uuid REFERENCES public.profiles(id),created_at timestamptz NOT NULL DEFAULT now(),CHECK(company_id IS NOT NULL OR sale_id IS NOT NULL OR order_id IS NOT NULL));
CREATE TABLE public.opportunity_scores(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),score integer NOT NULL CHECK(score BETWEEN 0 AND 100),explanation jsonb NOT NULL,weights_version integer NOT NULL,source text NOT NULL DEFAULT 'Dados próprios',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.settings(key text PRIMARY KEY,value jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES public.profiles(id),action text NOT NULL,entity_id uuid,entity_type text NOT NULL,metadata jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sales_date_idx ON public.sales(date);
CREATE INDEX activities_company_idx ON public.activities(company_id,created_at DESC);
CREATE INDEX followups_schedule_idx ON public.followups(scheduled_at) WHERE NOT done;
CREATE INDEX companies_seller_idx ON public.companies(salesperson_id) WHERE deleted_at IS NULL;
CREATE OR REPLACE FUNCTION public.is_axl_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND role='ADMIN') $$;
REVOKE ALL ON FUNCTION public.is_axl_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_axl_admin() TO authenticated;
-- Acesso inicialmente limitado ao administrador; outros perfis ficam bloqueados.
DO $$ DECLARE t text; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename IN ('profiles','salespeople','territories','companies','leads','customers','contacts','activities','followups','vendors','inventory_items','products','product_components','sales','sale_items','payments','orders','order_items','production_tasks','inventory_movements','purchases','purchase_items','expenses','commissions','goals','google_places','ranking_checks','routes','route_stops','attachments','opportunity_scores','settings','audit_logs') LOOP
EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
EXECUTE format('CREATE POLICY admin_access ON public.%I FOR ALL TO authenticated USING (public.is_axl_admin()) WITH CHECK (public.is_axl_admin())',t);
END LOOP; END $$;
CREATE POLICY own_profile_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid());
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
DO $$ DECLARE t text; BEGIN FOR t IN SELECT table_name FROM information_schema.columns WHERE table_schema='public' AND column_name='updated_at' LOOP EXECUTE format('CREATE TRIGGER updated_at_trigger BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()',t); END LOOP; END $$;
-- Usuários são criados em Supabase Auth. O primeiro ADMIN é provisionado pelo SQL Editor.
-- Não há rota pública que promova um usuário ao perfil ADMIN.
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES('axl-files','axl-files',false,10485760,ARRAY['image/png','image/jpeg','image/webp','application/pdf']) ON CONFLICT(id) DO NOTHING;
CREATE POLICY axl_files_admin ON storage.objects FOR ALL TO authenticated USING(bucket_id='axl-files' AND public.is_axl_admin()) WITH CHECK(bucket_id='axl-files' AND public.is_axl_admin());
COMMIT;
