export type Company = {
  id: string;
  name: string;
  legal_name: string;
  document: string;
  contact: string;
  phone: string;
  email: string;
  city: string;
  neighborhood: string;
  state: string;
  address: string;
  postal_code: string;
  segment: string;
  origin: string;
  notes: string;
  is_customer: number;
  is_lead: number;
  status: string;
  salesperson_id: string | null;
  place_id: string | null;
  created_at: string;
};
export type Product = {
  kind?: string;
  stock_inventory_id?: string;
  cost_known?: number;
  id: string;
  name: string;
  sku: string;
  category: string;
  description: string;
  price: number;
  cost: number;
  is_plate: number;
  active: number;
  uses_nfc: number;
  uses_acrylic: number;
  controls_stock: number;
  unit: string;
};
export type Sale = {
  cost_status?: string;
  revenue_allocated?: number;
  discount?: number;
  user_id?: string;
  date_label?: string;
  date_start?: string;
  date_end?: string;
  import_source?: string;
  cost_known?: number;
  payment_known?: number;
  id: string;
  number: number;
  company_id: string;
  company_name: string;
  salesperson_id: string | null;
  date: string;
  total: number;
  cost: number;
  profit: number;
  plates: number;
  paid: number;
  method: string;
  due_date: string;
  notes: string;
  commission: number;
  commission_rule: string;
};
export type Order = {
  responsible_id?: string;
  company_id?: string;
  item_snapshot?: string;
  id: string;
  sale_id: string;
  number: number;
  company_name: string;
  status: string;
  promised_date: string;
  notes: string;
  produced_at: string | null;
};
export type Inventory = {
  quantity_known?: number;
  cost_status?: string;
  cost_origin?: string;
  kind?: string;
  stock_confirmed_at?: string;
  id: string;
  name: string;
  unit: string;
  quantity: number;
  minimum: number;
  cost: number;
  supplier: string;
};
export type Activity = {
  id: string;
  company_id: string;
  type: string;
  description: string;
  created_at: string;
};
export type Followup = {
  id: string;
  company_id: string;
  company_name: string;
  date: string;
  reason: string;
  responsible: string;
  done: number;
};
export type Seller = {
  id: string;
  name: string;
  email: string;
  city: string;
  commission_type: string;
  commission_value: number;
};
export type Expense = {
  id: string;
  description: string;
  category: string;
  amount: number;
  date: string;
  paid: number;
};
export type Route = {
  id: string;
  name: string;
  date: string;
  salesperson_id: string | null;
};
export type Stop = {
  id: string;
  route_id: string;
  company_id: string;
  name: string;
  address: string;
  city: string;
  position: number;
  status: string;
};
export type Lot = {
  id: string;
  inventory_id: string;
  code: string;
  quantity: number;
  amount: number;
  freight: number;
  unit_cost: number;
  received: number;
  paid: number;
  paid_known: number;
  financial_date?: string;
  purchase_date?: string;
  receipt_status: string;
  notes: string;
  source_key?: string;
};
export type ContactEvent = {
  id: string;
  company_id: string;
  type: string;
  phone: string;
  text: string;
  result: string;
  user_name: string;
  created_at: string;
  next_at?: string;
};
export type State = {
  lotPayments?: { id: string; lot_id: string; amount: number; date: string }[];
  v2?: boolean;
  lots?: Lot[];
  contacts?: ContactEvent[];
  cash?: {
    id: string;
    type: string;
    amount: number;
    date: string;
    notes: string;
  }[];
  reservations?: {
    id: string;
    order_id: string;
    inventory_id: string;
    quantity: number;
    status: string;
  }[];
  counts?: {
    id: string;
    inventory_id: string;
    quantity: number;
    date: string;
    initial: number;
    notes: string;
  }[];
  orderEvents?: {
    id: string;
    order_id: string;
    type: string;
    user_name: string;
    notes: string;
    created_at: string;
  }[];
  proposals?: {
    id: string;
    company_id: string;
    text: string;
    amount: number;
    status: string;
  }[];
  imports?: {
    sha256: string;
    filename: string;
    count: number;
    plates: number;
    total: number;
    imported_at: string;
  }[];
  backend: "local" | "supabase";
  profiles: {
    id: string;
    name: string;
    email: string;
    role: string;
    created_at: string;
  }[];
  saleItems: {
    id: string;
    sale_id: string;
    product_id: string;
    product_name: string;
    quantity: number;
    price: number;
    cost: number;
    is_plate: number;
    components_snapshot: string;
    revenue_known?: number;
    line_total?: number | null;
    cost_status?: string;
    cost_origin?: string;
    unit_cost_precise?: number;
    cost_total?: number;
  }[];
  payments: {
    id: string;
    sale_id: string;
    amount: number;
    method: string;
    date: string;
  }[];
  companies: Company[];
  products: Product[];
  sales: Sale[];
  orders: Order[];
  inventory: Inventory[];
  activities: Activity[];
  followups: Followup[];
  salespeople: Seller[];
  expenses: Expense[];
  goals: { id: string; period: string; amount: number }[];
  components: {
    id: string;
    product_id: string;
    inventory_id: string;
    quantity: number;
  }[];
  movements: {
    id: string;
    name: string;
    quantity: number;
    type: string;
    description: string;
    created_at: string;
  }[];
  routes: Route[];
  stops: Stop[];
  audit: {
    id: string;
    name: string;
    action: string;
    entity_id: string;
    created_at: string;
  }[];
  weights: import("./domain").ScoreWeights;
};
